# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-30 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicle',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
