# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_auto_20180502_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicle',
            old_name='contributor_url',
            new_name='contributor_link',
        ),
        migrations.AddField(
            model_name='practicle',
            name='download_all_link',
            field=models.URLField(blank=True),
        ),
    ]
